# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'instagram-codepath' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for instagram-codepath
  pod 'Parse'
  pod 'AFNetworking'
  pod 'Parse/UI'
  pod 'DateTools'

  target 'instagram-codepathTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'instagram-codepathUITests' do
    # Pods for testing
  end

end
